services:
  - type: web
    name: my-app
    env: python
    buildCommand: "/opt/render/project/src/.venv/bin/python -m pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "/opt/render/project/src/.venv/bin/gunicorn app:app"